image: Visual Studio 2017

before_build:
  - gitversion /l console /output buildserver

build_script:
  - ps: .\build.ps1 $env:GitVersion_NuGetVersion

test_script:
  # Ensure template project itself builds correctly
  - ps: content\build.ps1

artifacts:
  - path: artifacts\*.nupkg
    name: NuGet

deploy:
  provider: Environment
  name: nuget.org
  on:
    appveyor_repo_tag: true
