{
 "title": "Generic Service",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Cluster", "query": "prometheus" },
   {
    "name": "Name",
    "query": "label_values(kube_pod_container_resource_requests_memory_bytes, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "Replicas running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(min(kube_deployment_status_replicas_available{deployment=\"$Name\"}) != bool 0) +\n(max(kube_deployment_status_replicas_unavailable{deployment=\"$Name\"}) == bool 0)"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"$Name\"})"
    }
   ]
  },
  { "title": "HTTP requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Status codes (per hour)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_backend_requests_total{backend=~\"$Name.*\",code=~\"2..\"}[1h]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(increase(traefik_backend_requests_total{backend=~\"$Name.*\",code=~\"3..\"}[1h]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(increase(traefik_backend_requests_total{backend=~\"$Name.*\",code=~\"4..\"}[1h]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(traefik_backend_requests_total{backend=~\"$Name.*\",code=~\"5..\"}[1h]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Response times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_backend_request_duration_seconds_sum{backend=~\"$Name.*\"}[1m])) /\nsum(increase(traefik_backend_requests_total{backend=~\"$Name.*\"}[1m]))",
     "legendFormat": "Response time"
    }
   ]
  },
  { "title": "Resource utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Memory usage (in percent)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{container_name=\"$Name\"}) by (pod_name) /\nscalar(min(kube_pod_container_resource_limits_memory_bytes{container=\"$Name\"}))",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "CPU usage (in percent)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 11, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name=\"$Name\"}[1m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  }
 ]
}