# Default configuration values
# For local development overrides: see launchSettings.json or docker-compose.override.yml
# For production overrides: see helmfile.yaml

Port: 80

Logging:
  LogLevel:
    Default: Debug
    Microsoft: Warning # Reduce ASP.NET Core verbosity

Policies:
  StartupRetries:
    - 00:00:15
    - 00:00:30

Database:
  ConnectionString: Data Source=myservice.db
