# This file contains default configuration.
#
# Additional config files:
#   dev:        appsettings.Development.yml
#   live:       appsettings.Production.yml
#   Kubernetes: helmfile.yaml
#   local dev:  launchSettings.json

Logging:
  LogLevel:
    Microsoft: Warning # Reduce ASP.NET Core verbosity

Policies:
  StartupRetries:
    - 00:00:15
    - 00:00:30

Authentication:
  ApiName: myservice

Database:
  ConnectionString: Data Source=myservice.db
