helmDefaults:
  force: true # Allow deploying over failed releases
  wait: true # Wait for all Pods to become ready

# Registers repos for use in requirements.yaml
repositories:
  - name: axoom-github
    url: https://axoom.github.io/charts/

# Installs charts
releases:
  - name: myvendor-myservice
    namespace: myteam
    chart: ./charts/myvendor-myservice

    values:
      - app:
          image:
            tag: '{{ requiredEnv "GitVersion_NuGetVersion" }}'
          ingress:
            enabled: true
            domain: 'myvendor-myservice.{{ requiredEnv "PUBLIC_CLUSTER_DOMAIN" }}'
          env:
            ASPNETCORE_ENVIRONMENT: '{{ env "ASPNETCORE_ENVIRONMENT" | default "Production" }}'
            Authentication__Authority: 'https://account.{{ requiredEnv "PUBLIC_CLUSTER_DOMAIN" }}'
            Authentication__ApiSecret: '{{ randAlphaNum 16 }}'
            ConnectionStrings__Database: 'Host=cloud-sql.cloud-sql.svc.cluster.local;User ID={{ requiredEnv "DATABASE_NAME" }};Password={{ requiredEnv "DATABASE_PASSWORD" }};Database={{ requiredEnv "DATABASE_NAME" }};Integrated Security=true;Pooling=true'
