# Runs the service in a production-like environment. Usually combined with other Compose files.
version: '2'

services:
  my_image:
    restart: always
    image: ${DOCKER_REGISTRY}/my_image:${VERSION}
