# Runs the service in a production-like environment. Usually combined with other Compose files.
version: '2.2'

services:
  my_service:
    restart: always
    image: ${DOCKER_REGISTRY}/my_service:${VERSION}
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Logging__LogTargets__0__Level=${LOG_LEVEL-Info}
