# Enables the Visual Studio debugger to attach to "Release" builds.
version: '2.1'

services:
  my_service:
    image: my_service:clrdbg
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
