# Specifies additional dependencies and exposes ports for local development/testing.
version: '3.4'

services:
  myvendor-myservice:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Logging__Format: Plain
    ports:
      - "12345:80"
    #   - "5000:5000"
