Logging:
  LogLevel:
    Default: Debug
    Microsoft: Warning # Reduce ASP.NET Core verbosity
  Format: Plain

Policies:
  StartupRetries:
    - 00:00:15
    - 00:00:30

Database:
  ConnectionString: Data Source=myservice.db
