Logging:
  ApplicationName: myservice
  Filter:
    # Reduce ASP.NET Core verbosity
    Microsoft: Warning
  LogTargets:
    0:
      Type: Console
      Async: true
      Format: Plain
      Level: Debug
